#! /usr/bin/env bash

# Print an error message
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

mesh_program="$cmd_dir/generate_mesh"
point_program="$cmd_dir/generate_random_point_cloud"

echo "Running generate_random_point_cloud"
$point_program -n 10 -m 1 || panic "generate point cloud failed"

#echo "Running generate_mesh for bunny"
#$mesh_program < $cmd_dir/bunny.xyz > $cmd_dir/bunny.off|| panic "generate mesh from bunny failed"

#echo "Running generate_mesh for test file"
#$mesh_program < $cmd_dir/pointcloud.xyz > $cmd_dir/pointcloud.off || panic "generate mesh from point cloud failed"
