#! /usr/bin/env bash

# Print an error message
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

mesh_program="$cmd_dir/generate_mesh"
point_program="$cmd_dir/generate_random_point_cloud"

echo "Running generate_random_point_cloud"
$point_program > pointcloud.xyz|| panic "generate mesh program failed"

echo "Running generate_mesh"
$mesh_program < bunny.xyz > bunny.off|| panic "generate point cloud program failed"